import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={cn(`${geistSans.variable} ${geistMono.variable}`, 'bg-gray-100')}>
        <main className="mx-auto flex h-full max-w-[600px] flex-col bg-white shadow-2xl">
          <header className="w-full bg-theme-primary py-4 text-center font-bold text-white">
            <h1 className="text-lg tracking-wide">Pawfolio</h1>
          </header>
          <div className="flex-1">{children}</div>
          <footer className="w-full bg-white/70 py-2 text-center text-sm text-theme-secondary/70">
            &copy; 2025 Pawfolio Company
          </footer>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
